spring:
  config:
    import:
      - optional:file:.env[.properties]    # to run app by main class or jar from the IDE
      - optional:file:../.env[.properties] # to run app by gradle task bootRun

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    dev.arhor: DEBUG
